site_name: b3-exmo's notes

theme:
  name: 'material'
  custom_dir: overrides
  primary: custom
  palette:
  # Light mode
  - media: "(prefers-color-scheme: light)"
    scheme: obs-light
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  # Dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: obs-dark
    toggle:
      icon: material/brightness-7
      name: Switch to light mode

  features:
  - navigation.indexes
  - navigation.instant
  - navigation.instant.progress
  - navigation.path
  - navigation.top
  - navigation.tracking
  - toc.follow

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

extra:
  analytics:
    provider: google
    property: G-WSB0F0E5MY
