site_name: b3-exmo's notes

theme:
  name: material
  icon:
    logo: mg/bee-icon.png
  favicon: img/bee-icon.png
  custom_dir: overrides
  palette:
  # Light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  # Dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  font:
    text: Inter
    code: Fira Code

  features:
  - navigation.indexes
  - navigation.instant
  - navigation.instant.progress
  - navigation.path
  - navigation.top
  - navigation.tracking
  - toc.follow

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

extra_css:
  - stylesheets/extra.css

nav:
  - ⛪ Home: index.md
  - ✍️ My own experience: My own experience.md
  - ✝️ Christianity:
    - Christianity/Christianity.md
    - 🪦 Exaltation & Afterlife: Christianity/Exaltation.md
    - 🌄Historicity: Christianity/Historicity.md
    - 👻 Holy Spirit's Promptings: Christianity/Holy Spirit Promptings.md
    - 😈 Satan: Christianity/Satan.md
    - 🌩 Theology: Christianity/Theology.md
    - ❓ What are blessings?: Christianity/What are blessings.md
  - 💬 Commentated Documents:
    - 💒 D&C 132: Commentated Docs/DC 132.md
    - 🤔 Doubts and Truth: Commentated Docs/Doubts and Truth.md
    - 🤡 Fourteen Fundamentals in Following the Prophet: Commentated Docs/14 Fundamentals.md
    - 😵 It's too sacred!: Commentated Docs/Too Sacred.md
    - 💭 What Do We Mean When We Say the Church Is True?: Commentated Docs/What Do We Mean When We Say the Church Is True.md
  - 🤨 Critical Thinking:
    - Critical thinking/Critical Thinking.md
    - 🧠 Cognitive Bias: Critical thinking/Cognitive Bias.md
    - 🥺 Emotional Thinking: Critical thinking/Emotional Thinking.md
    - 👎 Falsifiability: Critical thinking/Falsifiability.md
    - ♟️ Logical Fallacies: Critical thinking/logical-fallacies.md
    - 🧪 Shelf: Critical thinking/Shelf.md
  - 👥 Culture:
    - Culture/Culture.md
    - 😬 Anxiety: Culture/Anxiety.md
    - 💔 God's Conditional Love: Culture/Gods Conditional Love.md
    - 😇 Infallibility: Culture/Infallibility.md
    - ☝️🤓 Name "Mormon": Culture/Name Mormon.md
    - ✔️ Scrupulosity: Culture/Scrupulosity.md
    - ⚧️ Sexuality & Repression: Culture/Sexuality Repression.md
    - 💪 Strengthening Church Members Committee: Culture/Strengthening Church Members Committee.md
    - 😔 Too Sacred to Share: Culture/Too Sacred to Share.md
    - ✅ True: Culture/True.md
  - 📐 Doctrines:
    - 🌊 Baptism: Doctrines/Baptism.md
    - 🪄 Becoming Gods: Doctrines/Becoming Gods.md
    - 🩲 Garments: Doctrines/Garments.md
    - 👩‍🤝‍👩 Polygamy: 
      - Doctrines/Polygamy/Polygamy.md
      - 🛏 Consummation: Doctrines/Polygamy/Consummation.md
      - 👧 Helen Mar Kimball: Doctrines/Polygamy/Helen Kimball.md
      - 🥩💱 Meat Commerce: Doctrines/Polygamy/Meat commerce.md
      - 😏 Sealing: Doctrines/Polygamy/Sealing.md
  - 👨‍💼 Prophets:
    - Prophets/Prophets.md
    - 🌱 Restoration: Prophets/Restoration.md
    - 😍 Joseph Smith: 
      - Prophets/Joseph Smith/Joseph Smith.md
      - 🎓 Education: Prophets/Joseph Smith/Education.md
      - 🕶 First Vision: Prophets/Joseph Smith/First Vision.md
      - 🎣 Kinderhook Plates: Prophets/Joseph Smith/Kinderhook Plates.md
    - 😤 Brigham Young:
      - Prophets/Brigham Young/Brigham Young.md
      - 🩸 Blood Atonement: Prophets/Brigham Young/Blood Atonement.md
      - 🥊 Vs. Emma Smith: Prophets/Brigham Young/Vs Emma Smith.md
    - 🇺🇸 Ezra Taft Benson: Prophets/Ezra Taft Benson/Ezra Taft Benson.md
  - 🏁 Race: 
    - Race/Race.md
    - 🤼 Race in Scripture: Race/Race in scripture.md
    - 🎩 "Skin of Blackness": Race/Skin of blackness.md
    - 🌶 Various Quotes: Race/Various Quotes.md
  - 📚 Scripture: 
    - 📑 Bible: Scripture/Bible.md
    - 📘 Book of Mormon:
      - Scripture/Book of Mormon/Book of Mormon.md
      - 🙅‍♂️ Antichrist: Scripture/Book of Mormon/Antichrist Korihor.md
      - 🔃 BoM Changes: Scripture/Book of Mormon/BoM Changes.md
      - 🤷 Isaiah: Scripture/Book of Mormon/Isaiah.md
      - ❓ Logistial Problems: Scripture/Book of Mormon/logistical-problems.md
      - 🤥 Plagiarism: Scripture/Book of Mormon/Plagiarism.md
      - ♀️ Representation of Women: Scripture/Book of Mormon/Representation of Women.md
      - ⚓ Seafaring: Scripture/Book of Mormon/Seafaring.md
      - 🤖 Technology: Scripture/Book of Mormon/Technology.md
      - 🍽 The Plates: Scripture/Book of Mormon/The Plates.md
      - 👅 Book of Mormon Translation: Scripture/Book of Mormon/Translation.md
    - 👴 Book of Abraham: Scripture/Book of Abraham.md
  - 💵 Tithing:
    - Tithing/Tithing.md
    - 🔎 Audits: Tithing/Audits.md
    - 💸 Charitable Giving: Tithing/Charitable Giving.md
    - 🗣️ In General Conference: Tithing/In General Conference.md
    - 🧑‍⚖️ SEC: 
      - Tithing/SEC/SEC.md
      - 📃 SEC Order: Tithing/SEC/SEC Order.md
      - 🗣 WSJ Interview: Tithing/SEC/WSJ Interview.md
  - 📜 LDS Historians: Historians.md
  - 📝 Poetry: Poetry.md
  - 🔗 Sources & More Material: Sources and Links.md
  - 🗒️ TODO: TODO.md

extra:
  analytics:
    provider: google
    property: G-WSB0F0E5MY
